name: 'DockerImagePublish'
description: 'Build, tag and push docker images under certain conditions.'
inputs:
    dockerFileName:
        description: 'Name of Dockerfile'
        default: 'Dockerfile'
        required: true
    dockerFilePath:
        description: 'Relative path to DockerFile'
        default: ''
        required: true
    gitTag:
        description: 'Whether to create an image tag for a git tag.'
        default: 'true'
    gitTagPrefix:
        description: 'Prefix for matching git tags'
        default: ''
    gitUser:
        description: 'Git user'
        default: ${{ github.actor }}
    gitPassword:
        description: 'Git password'
        default: ${{ github.token }}
    registryHost:
        description: 'Registry host'
        default: 'ghcr.io'
        required: true
    registryUser:
        description: 'Registry user'
        default: ${{ github.actor }}
    registryPassword:
        description: 'Registry password'
        default: ${{ github.token }}
    registryRepository:
        description: 'Registry repository full name (e.g. project/repository)'
        default: ${{ github.repository }}
        required: true
    registryTag:
        description: 'Registry image tag (e.g. latest)'
        default: ''
    cleanup:
        description: 'Delete the built image at the end'
        default: 'true'
    token:
        description: 'Token to access GitHub API'
        default: ${{ github.token }}
    buildArgs:
        description: 'Provide additional build args'
        default: ''

runs:
    using: 'docker'
    image: 'Dockerfile'
